### ISSUE TITLE
highlight html

### ISSUE THREAD

**Issue by leandrw** [11ty/eleventy-plugin-syntaxhighlight#11]
I have one code snippet in a .MD file
```
```html
<div id="container" class="my-container">
  I want my <span class="text red">color</span>
</div>

<style>
#container span {
  color: blue;
}

.my-container .text.red {
  color: red;
}
</style>
```

But the HTML part of this snippet is being rendered as HTML:
![image](https://user-images.githubusercontent.com/1456009/54884070-5362ac00-4e4b-11e9-8745-65aab0d4cd40.png)

**Comment by jfitzsimmons2** [comment]
If anyone else comes across this from Google, my issue was that in my .eleventy.js file I had

```
markdownTemplateEngine: "liquid",
```

in my options, so instead of using the Markdown method using backticks, I used the Liquid method

```
{% highlight html %}
<html></html>
{% endhighlight %}
```

**Comment by verlok** [comment]
Thanks, @jfitzsimmons2
