### ISSUE TITLE
Multiline comments not working

### ISSUE THREAD

**Issue by pianomanfrazier** [11ty/eleventy-plugin-syntaxhighlight#12]
When I try to add a multi line comment in any c like language it doesn't render properly. I didn't add any extensions to Prism.

```c
/*
  This is a
  Block comment
*/
```

![screenshot](https://user-images.githubusercontent.com/9702617/56350659-89fcbf80-6188-11e9-8447-200cc8b6bf64.png)

**Comment by zachleat** [comment]
Is this a prism thing or do you think it's limited to this plugin?

**Comment by pianomanfrazier** [comment]
I thought of that. I didn't dive into how the plugin works. I just know that I applied the plugin and multi-line comments were not working. I'm not sure how to isolate the problem to just Prism or the plugin.

My setup for Eleventy was pretty simple. You can see my `.eleventy.js` file at my repo [here](https://github.com/pianomanfrazier/lilypond-in-markdown/blob/53caad5ec054e093452459343f380cebe76bb8b4/.eleventy.js#L22). There I have my own language extension. However, I did try it without and then tried using C code and it still didn't work.

I am injecting Typography.js onto the page but that only affects the CSS, not the Prism parsing.

I did notice though that the Prism version used in the plugin (v1.15.0) is not the latest (v1.16.0). Again, I doubt this is the issue though.

**Comment by zachleat** [comment]
Not at a computer currently, can you compare with https://prismjs.com/test.html#language=javascript

What language did you pass in from your content?

**Comment by pianomanfrazier** [comment]
It must be the plugin. It works on prismjs. I cloned the [Eleventy Base Blog](https://github.com/11ty/eleventy-base-blog) and multi line comments don't work there either.

![prism_screenshot](https://user-images.githubusercontent.com/9702617/56403939-08a53b80-6221-11e9-9907-118bdc5facd1.png)

And here is the same input on the base blog. I added the snippet to `posts/firstpost.md`

![base_blog](https://user-images.githubusercontent.com/9702617/56403944-10fd7680-6221-11e9-8b12-b476fcf42d66.png)

**Comment by pianomanfrazier** [comment]
I wonder if this is related to #9 The new line in the middle of a parsed element is throwing off the parsing.

**Comment by pianomanfrazier** [comment]
It appears that the highlight line is interfering with multiline elements in the code blocks. [markdownSyntaxHighlight.js](https://github.com/11ty/eleventy-plugin-syntaxhighlight/blob/01d79134e172b26da5e5175a44fe30f57736e96b/src/markdownSyntaxHighlight.js#L34)

![highlight-line-bad](https://user-images.githubusercontent.com/9702617/56405305-ffb86800-6228-11e9-9127-588b4f2a7a66.png)
