### ISSUE TITLE
Confusing error on unrecognized language

### ISSUE THREAD

**Issue by porglezomp** [11ty/eleventy-plugin-syntaxhighlight#18]
If I use an unrecognized syntax, for instance:

File `index.md`:
````markdown
```asdfl
```
````

Then the error is confusing.
```
Language does not exist asdfl
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk (and markdown) template ./index.md

`TemplateContentRenderError` was thrown
> Cannot read property 'rest' of undefined
```

The first line mentions that the language doesn't exist, but I didn't realize for quite a while that that warning was the cause of the later fatal error.

**Expected Behavior:**
Unrecognized languages should give a warning and then simply fail to highlight that syntax.

**Comment by zachleat** [comment]
That console.warn actually comes from Prism, unfortunately. https://github.com/PrismJS/prism/issues/2145

But we _can_ clean up the error message.
