### ISSUE TITLE
Line highlight is being added to the wrong lines

### ISSUE THREAD

**Issue by ccverak** [11ty/eleventy-plugin-syntaxhighlight#26]
I realized that in version 3.0.1, the `mark` wrapper along with the `highlight-line-active` are being added to the line you declared plus 1.

Ex. 

using ```  js/3

``` js/3
console.log(...);
console.log(...);
console.log("should be here");
console.log("but it highlights this line");
```
I fixed it locally by changing this line https://github.com/11ty/eleventy-plugin-syntaxhighlight/blob/master/src/markdownSyntaxHighlightOptions.js#L30
with `let lineContent = highlights.getLineMarkup(j + 1, line);`

Is this a problem that everybody is facing or is there something wrong on my local setup?

**Comment by ccverak** [comment]
Fixed in https://github.com/11ty/eleventy-plugin-syntaxhighlight/pull/27

**Comment by zachleat** [comment]
Hey, sorry about this—the line numbers are zero-indexed. I added a bunch of notes to the docs at https://www.11ty.dev/docs/plugins/syntaxhighlight/ and they’ll go live with the next deploy.
