### ISSUE TITLE
Unsupported diff-* highlighting

### ISSUE THREAD

**Issue by RReverser** [11ty/eleventy-plugin-syntaxhighlight#28]
Prism allows convenient diff line highlighting with preservation of underlying syntax highlighting via a Diff Highlight plugin: https://prismjs.com/plugins/diff-highlight/

However, trying to use it via 11ty via e.g. ```` ```diff-javascript ```` tag currently fails with

```
`TemplateContentRenderError` was thrown
> "diff-javascript" is not a valid Prism.js language for eleventy-plugin-syntaxhighlight

`Error` was thrown:
    Error: "diff-javascript" is not a valid Prism.js language for eleventy-plugin-syntaxhighlight
        at module.exports (/mnt/c/src/web.dev/node_modules/.pnpm/@11ty/eleventy-plugin-syntaxhighlight@3.0.1_@11ty+eleventy@0.11.0/node_modules/@11ty/eleventy-plugin-syntaxhighlight/src/PrismLoader.js:11:11)
...
```

Looks like this might require some special handling similarly to TypeScript tag?

**Comment by peterjcaulfield** [comment]
See https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/46

**Comment by RReverser** [comment]
@peterjcaulfield Right, I'm aware of that manual syntax, but that's different, and very hard to maintain for complex diffs. Whereas real diff syntax support can be applied to unifieddiffs copied from Git.

**Comment by peterjcaulfield** [comment]
Yep gotcha. It seems like there are issues with a number of Prism plugins when [used in a Node env](https://github.com/PrismJS/prism/issues/1171).

**Comment by zachleat** [comment]
Starting with now-available v3.2.1 of this plugin, you can use `diff-` on the prefix of your language and Eleventy will use the official Prism.js diff-highlight plugin. Look to https://www.11ty.dev/docs/plugins/syntaxhighlight/ soon for the official docs on this.

**Comment by RReverser** [comment]
Amazing, thanks!

**Comment by davidpmccormick** [comment]
With the following in my `.md` file

\```diff-js
function test(a) {
\+	const b = a + 1;
	const anotherThingThatIWantToBeHighlighted = 'nope';
\-	return b;
}
\```

I end up with this (only the +/- lines have been tokenized). Should this work now and/or am I missing something?

<img width="827" alt="image" src="https://user-images.githubusercontent.com/1394592/212118463-d31a9f79-9651-45cb-bbea-8fde1950e721.png">
