### ISSUE TITLE
Loading PrismJS in Eleventy config breaks plugin

### ISSUE THREAD

**Issue by jordanthornquest** [11ty/eleventy-plugin-syntaxhighlight#37]
Hello, folks.

To be honest, I'm not sure if this is an expected behavior, or something unintended. In a recent project, I was using `eleventy-plugin-syntaxhighlight` to provide straightforward highlighting for markdown files. However, I also created a shortcode for creating previews of code snippets and their processed output. Essentially, what Bootstrap does in their documentation.

![Screen Shot 2020-10-28 at 5 19 01 PM](https://user-images.githubusercontent.com/1444819/97506978-d316fd80-1941-11eb-8f33-829b464aa5f5.png)

For this shortcode, I ended up needing to load my own instance of PrismJS, and the languages I'd need to utilize. Here's a shorthand of what was going on in my config.

`eleventy.js`
```js
// Load libraries and dependencies
const prism = require("prismjs");
const loadLanguages = require("prismjs/components/");
loadLanguages(['html', 'jsx', 'json', 'twig', 'velocity']);
const syntaxHighlight = require("@11ty/eleventy-plugin-syntaxhighlight");

module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(syntaxHighlight);

  // Code examples shortcode
  eleventyConfig.addPairedShortcode("example", function(content, title, show_preview, show_markup) {
    let highlightedContent = prism.highlight(content.trim(), prism.languages["html"], "html");

    let lines = highlightedContent.split("\n");
    lines = lines.map(function(line, j) {
      return line;
    });

    return outdent`
      <div class="card docs-example">
        ${title ? `<h6 class="card-header">${title}</h6>` : `<h6 class="card-header">Example</h6>`}
        <div class="card-body">
          ${show_preview ? `<div class="docs-example-content">${content}</div>` : ``}
          ${show_markup ? `<div class="docs-example-markup"><pre class="language-html"><code class="language-html">` + lines.join("<br>") + "</code></pre></div>" : ``}
        </div><!-- /.card-body -->
      </div><!-- /.docs-example -->
    `
  });

  // And so on
}
```

In one of my markdown files, I attempted to use `eleventy-plugin-syntaxhighlight` to style a `bash` script. What I've discovered is that, by loading PrismJS for use with my shortcode, I inadvertently caused the `eleventy-plugin-syntaxhighlight` plugin to no longer load the correct languages. I received an error in my console explaining that `bash` was not an available language for PrismJS. 

I ran in circles for a bit before thinking to remove my shortcode and the `const prism = require("prismjs");` module. I think the error is occurring either from loading Prism in the config, or by loading `const loadLanguages = require("prismjs/components/");` in the config. Even if I removed my shortcode and kept the module imports, the same error would occur. Removing the modules caused the plugin to successfully process the `bash` highlighting without issue.

Any thoughts on whether or not this is expected, or how to use both functions while maintaining compatibility?

**Comment by zachleat** [comment]
Eleventy has a bunch of Prism-specific loading code to facilitate its use in Node.

I think your best bet here is a programmatic use of this plugin. We do provided a `pairedShortcode` export that you can use, e.g.

```js
const syntaxHighlight = require("@11ty/eleventy-plugin-syntaxhighlight");
const eleventyPrism = syntaxHighlight.pairedShortcode;

module.exports = function(eleventyConfig) {
  eleventyConfig.addPlugin(syntaxHighlight);

  // Code examples shortcode
  eleventyConfig.addPairedShortcode("example", function(content, title, show_preview, show_markup) {
    return outdent`
      <div class="card docs-example">
        ${title ? `<h6 class="card-header">${title}</h6>` : `<h6 class="card-header">Example</h6>`}
        <div class="card-body">
          ${show_preview ? `<div class="docs-example-content">${content}</div>` : ``}
          ${show_markup ? `<div class="docs-example-markup">${eleventyPrism(content), "html"}</div>" : ``}
        </div><!-- /.card-body -->
      </div><!-- /.docs-example -->
    `
  });

  // And so on
}
```
