### ISSUE TITLE
Make it possible to pass custom Prism plugins

### ISSUE THREAD

**Issue by mathiasbynens** [11ty/eleventy-plugin-syntaxhighlight#4]
Can haz a way to pass custom Prism plugins to this 11ty plugin? Maybe this can be solved generically by allowing something like this in 11ty's plugin system:

```diff
-eleventyConfig.addPlugin(syntaxHighlight);
+eleventyConfig.addPlugin(syntaxHighlight, initializer);
```

For this particular plugin, `initializer` would be a function that gets called with the `Prism` object as an argument. Users could then do something like:

```js
const initializer = (Prism) => {
  Prism.languages.myCustomLanguage = /* */;
};
eleventyConfig.addPlugin(syntaxHighlight, initializer);
```

What do you think?

**Comment by zachleat** [comment]
I think that’s a good idea, yeah. :+1:

Maybe the `this` inside the callback should be the eleventyConfig object too?

**Comment by zachleat** [comment]
I’m thinking plugins may want to expose multiple initializer arguments…

Any recommendations stylistically on `({ Prism, otherThing })` vs `(Prism, otherThing)`?

I think I like the latter better as it doesn’t seem to be as tightly coupled to the upstream plugin’s variable naming. The drawback there is that it has strict argument order ¯\_(ツ)_/¯

**Comment by mathiasbynens** [comment]
I strongly prefer `({ Prism, otherThing })`. Variable naming is part of the plugin’s API design.

**Comment by zachleat** [comment]
https://github.com/11ty/eleventy-plugin-syntaxhighlight#options
