### ISSUE TITLE
Alternate method for line highlighting

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-syntaxhighlight#42]
Thought this was really interesting and didn’t require modification of the source to wrap/add divs, it’s a separate element:
![image](https://user-images.githubusercontent.com/39355/103044320-b6fc9a80-4545-11eb-848e-7f395b57ae75.png)

As seen on https://rollup-plugin-vue.vuejs.org/examples.html

**Comment by siimpragi** [comment]
Hi! It sure is an interesting way to achieve line highlighting. So I looked into it. It seems the wrapping `<div>`-s were dropped in favor of `<mark>`, `<del>`, and `<ins>` in #7. Since those tags are all nice and semantic, I wonder if there really are any reasons to go forward with this?

**Comment by zachleat** [comment]
Closing as stale. I think the now-bundled diff- plugin is the better way forward here https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/28
