### ISSUE TITLE
Major issue with syntax-highlight plugin for multi-line code blocks

### ISSUE THREAD

**Issue by tannerdolby** [11ty/eleventy-plugin-syntaxhighlight#43]
@zachleat Everything that is being highlighted by `eleventy-plugin-syntaxhighlight` on [11ty.dev](https://www.11ty.dev) has some issues with the styling. 

Each of the multi-line code blocks are formatted into a single line. This issue is probably happening for everyone using the plugin, as I first noticed it on my own website.

Also, all of the `<pre>` tags have an extra space at the beginning of the `class` declaration like this (which I don't think matters but just wanted to note everything I saw)
```
<pre class=" language-html">
```
Screenshot of issue:
<img width="1024" alt="Screen Shot 2020-12-12 at 1 26 21 PM" src="https://user-images.githubusercontent.com/48612525/101995272-a9116480-3c7d-11eb-9b8f-129cccf222c7.png">

The above code snippets are supposed to be multi line but obviously they are not. 

I tried to tweak the CSS in my `prism.css` file locally to get the multi-line format to come back but I'm still trying to figure out where exactly the problem is at.

**Comment by zachleat** [comment]
Moved to `eleventy-plugin-syntaxhighlight` repo

**Comment by tannerdolby** [comment]
For anyone looking, here is a link to [issue #43](https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/43) over in `eleventy-plugin-syntaxhighlight`
