### ISSUE TITLE
Chrome ignores br tags to make a new highlight line

### ISSUE THREAD

**Issue by jeremenichelli** [11ty/eleventy-plugin-syntaxhighlight#45]
Not an issue of the plugin itself, but I noticed that Chrome removes `br` tags from a resulting code tag which was highlighted. Here's the exact same page, first on FIrefox and then on Chrome:

**Firefox**

![Captura de pantalla 2021-01-10 a la(s) 12 37 43](https://user-images.githubusercontent.com/3856481/104121707-acf9da80-5340-11eb-85b8-daac2f30a600.png)

**Chrome**

![Captura de pantalla 2021-01-10 a la(s) 12 38 08](https://user-images.githubusercontent.com/3856481/104121714-b5eaac00-5340-11eb-92f5-ba0e9aedf4a0.png)

This test page has no JavaScript or CSS.

Here's the reproduction case from above, if you want to run it locally:

[test.zip](https://github.com/11ty/eleventy-plugin-syntaxhighlight/files/5792527/test.zip)

My advice here would be to move the default `lineSeparator` option to `\n` and fire a warning if the user sets it to `<br>` in the mean time, as the output of the package it's broken out of the box because of this.

If we decide this is the way we want to go I'm more than happy to create a PR.

**Comment by jouni-kantola** [comment]
@jeremenichelli Do you by any chance have the axe plugin installed? See details in #43. Try a plugin free browser tab.

**Comment by jeremenichelli** [comment]
Oh my, that was it, can't believe I missed that thing. I thought I switched off everything to isolated the test case. Thanks a lot for jumping in @jouni-kantola

**Comment by jouni-kantola** [comment]
Great! I had already changed my setup's newlines before the axe issue was found.
```js
eleventyConfig.addPlugin(syntaxHighlightPlugin, {
  lineSeparator: "\n",
});
```
It works OK, but I'll change it back to default once https://github.com/dequelabs/axe-core/issues/2711 is closed. See below screenshots from Safari.

With `\n` newlines:
![\n newlines](https://user-images.githubusercontent.com/2670127/104134192-734cc200-5388-11eb-83bf-1dfbaa4ae8ca.png)

With default newlines (looks as expected):
![Default newlines](https://user-images.githubusercontent.com/2670127/104134260-c6267980-5388-11eb-9384-a213493a08b3.png)

**Comment by jeremenichelli** [comment]
Yeah I pushed the same fix by the time I wrote this issue. Thanks again for the pointer, I'll follow that issue.
