### ISSUE TITLE
Is there a way to add Prism plugins?

### ISSUE THREAD

**Issue by sarunw** [11ty/eleventy-plugin-syntaxhighlight#58]
I want to use https://prismjs.com/plugins/keep-markup/ but can't find a way to do this with eleventy-plugin-syntaxhighlight. Is this possible?

**Comment by boehs** [comment]
duplicate of https://github.com/11ty/eleventy-plugin-syntaxhighlight/issues/4

**Comment by zachleat** [comment]
Yeah #4 is the thing! Note that some prism.js plugins seem to require clientside operation 👀
