### ISSUE TITLE
Providing a default language for fenced code blocks

### ISSUE THREAD

**Issue by mattrossman** [11ty/eleventy-plugin-syntaxhighlight#66]
# Use case

In many markdown editors, I can write a fenced code blog and receive plaintext code styling without specifying a language.

E.g. writing this in GitHub markdown:

<pre><code>```
This is some plain text
```
</code></pre>

Looks like this:

```
This is some plain text
```

Currently, when no language is specified on a fenced code block, this plugin outputs plain `<pre>` and `<code>` tags without a `"language-*"` class applied. In many Prism themes, such as the [prism-okaidia](https://unpkg.com/prismjs@1.20.0/themes/prism-okaidia.css) theme shown in the [plugin docs](https://www.11ty.dev/docs/plugins/syntaxhighlight/), this means the code block will not receive any styling. This is unexpected behavior for me.

# Proposed Solution

To avoid breaking changes, I propose adding a `defaultLanguage` plugin option, which users may want to set to `"plain"`. That way a generic code block like this:

<pre><code>```
This is some plain text
```
</code></pre>

could be rendered as

```html
<pre class="language-plain"><code class="language-plain">
This is some plain text
</code></pre>
```

# Additional Context

Initially I thought I could set default languages like so:

```js
eleventyConfig.addPlugin(pluginSyntaxHighlight, {
    preAttributes: {
      class: "language-plain",
    },
    codeAttributes: {
      class: "language-plain",
    },
});
```

However, as brought up in #52 this does not work. Resolving that issue could also resolve this one.

**Comment by AleksandrHovhannisyan** [comment]
Big +1 from me on this; it's mainly why I switched to prism in the meantime.

**Comment by AleksandrHovhannisyan** [comment]
Oh, maybe not! It sounds like this should be possible with the `init` option.

**Comment by zachleat** [comment]
Just to be clear, I mean something like:

```
eleventyConfig.addPlugin(pluginSyntaxHighlight, {
    preAttributes: {
      class: ({language}) => `language-${language || "plain"}`,
    },
});
```

**Comment by AleksandrHovhannisyan** [comment]
Oh, yup, that should work! Thanks.

**Comment by zachleat** [comment]
Closing this one as fixed by #52 and #50 thanks y’all

**Comment by andreas-mausch** [comment]
Code blocks without language are still rendered without a language, even with this:

```
eleventyConfig.addPlugin(pluginSyntaxHighlight, {
    preAttributes: {
      class: ({language}) => `language-${language || "text"}`,
    },
});
```

Am I doing something wrong?
I suspect the lib returns here already:
https://github.com/11ty/eleventy-plugin-syntaxhighlight/blob/7b7b547fff07f2e60d91c0a7ed3bba1938dbc057/src/markdownSyntaxHighlightOptions.js#L8-L11

and my preAttributes-class-function is never called.

The function is called on code blocks with a language specified though.

For convenience, I'd even prefer the `defaultLanguage` option as suggested by @mattrossman

**Comment by edwardhorsford** [comment]
I see the same as @andreas-mausch - code blocks with languages already defined get the pre-attributes, but those with no languages defined get nothing.

**Comment by Nekkowe** [comment]
Yeah, same here. 
@zachleat In light of this, if possible, could you please reopen this issue?
