### ISSUE TITLE
Add prismjs alias for `nunjucks` mapped to `jinja2`

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-syntaxhighlight#68]
> Nunjucks is essentially a port of [jinja2](http://jinja.pocoo.org/docs/)

https://mozilla.github.io/nunjucks/templating.html

**Comment by zachleat** [comment]
Both `njk` and `nunjucks` will be aliased to `jinja2` on 4.1.0+

**Comment by edwardhorsford** [comment]
@zachleat this doesn't seem to be working correctly for me, though it does answer why `njk` and `nunjucks` aren't erroring for me.

From my reading of this, when I use `nunjucks` it should look the same as `jinja2` however they don't!

With `nunjucks`:
![Screenshot 2024-01-25 at 18 21 50](https://github.com/11ty/eleventy-plugin-syntaxhighlight/assets/2204224/cd54c194-7d05-493c-8464-c29a57cab450)

With `jinja2`:
![Screenshot 2024-01-25 at 18 22 26](https://github.com/11ty/eleventy-plugin-syntaxhighlight/assets/2204224/f5a19683-b041-46ab-89e8-cfdaa62e1c6c)

It's clearly doing *something* with the highlighting, but it's not correct, and it's not the same as `jinja2`. I observe the same when used as a shortcode and when used with markdown backticks. Using plugin v5.0.0
