### ISSUE TITLE
Default rendering with newlines and ins/del/mark

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-plugin-syntaxhighlight#8]
After #5 and #7 were merged, I’m now thinking about the best way to style the line highlighter to make it render how it used to with full width background colors.

## Previous behavior on eleventy-base-blog:
![image](https://user-images.githubusercontent.com/39355/46146742-2ed5a080-c229-11e8-8aa9-afd7247d3977.png)

## New behavior:
This is what it renders like without CSS (this is showing default styles for ins/del/mark, which are okay). I’ve added a few newlines in there just to see how #5 would look too (those were not in the previous behavior screenshot):
![image](https://user-images.githubusercontent.com/39355/46146850-752aff80-c229-11e8-8028-83004b5c8694.png)

This is what it looks like on `eleventy-base-blog` after removing the ins/del/mark styles:
![image](https://user-images.githubusercontent.com/39355/46148132-fdf76a80-c22c-11e8-969c-e5f41f8d65c4.png)

## The `display: block` Problem:
When using `.highlight-line { display: block; }` to get full width highlights, the problem exhibits itself:
![image](https://user-images.githubusercontent.com/39355/46147931-73af0680-c22c-11e8-8c82-9093053b672f.png)

![image](https://user-images.githubusercontent.com/39355/46147656-b3c1b980-c22b-11e8-8571-579d9323c27a.png)

If I move the `<br>` inside of the `highlight-line` elements, I get what I want with `display: block;`
![image](https://user-images.githubusercontent.com/39355/46147886-54b07480-c22c-11e8-99b5-903daad90e4c.png)

![image](https://user-images.githubusercontent.com/39355/46147879-4febc080-c22c-11e8-88d1-8f856d02689f.png)

Would it be better to move the `<br>`? Or to use CSS to hide the `<br>` altogether when using `display: block;`

**Comment by zachleat** [comment]
cc @mathiasbynens

**Comment by zachleat** [comment]
You can see what I mean in https://github.com/11ty/eleventy-plugin-syntaxhighlight/compare/inner-br?expand=1

**Comment by mathiasbynens** [comment]
Hmm… E.g. `<mark>foo bar<br></mark>` is weird to me, since the line break isn’t really part of what you’re trying to highlight.

IMHO think CSS is the right layer to solve this.

**Comment by zachleat** [comment]
Alright yeah, that makes sense to me. The line highlighting CSS (which is what needs `display: block` anyway) can package all this stuff together.
